# Generated by Django 3.2.9 on 2022-01-14 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearn', '0020_topicprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='requiredprogress',
            field=models.IntegerField(default=0),
        ),
    ]
